export const QuizData = [
  {
    prompt: "What is the output of: print(type([]))?",
    optionA: "<class 'list'>",
    optionB: "<class 'array'>",
    optionC: "<class 'tuple'>",
    optionD: "<class 'set'>",
    answer: "A",
  },
  {
    prompt: "Which keyword is used to define a function in Python?",
    optionA: "func",
    optionB: "def",
    optionC: "function",
    optionD: "lambda",
    answer: "B",
  },
  {
    prompt: "What is the correct file extension for Python files?",
    optionA: ".pyt",
    optionB: ".pyth",
    optionC: ".py",
    optionD: ".ptn",
    answer: "C",
  },
  {
    prompt: "Which data type is immutable in Python?",
    optionA: "List",
    optionB: "Dictionary",
    optionC: "Set",
    optionD: "Tuple",
    answer: "D",
  },
  {
    prompt: "What is the output of: len('Python')?",
    optionA: "5",
    optionB: "6",
    optionC: "7",
    optionD: "None",
    answer: "B",
  },
  {
    prompt: "Which keyword is used for exception handling?",
    optionA: "catch",
    optionB: "error",
    optionC: "try",
    optionD: "except",
    answer: "D",
  },
  {
    prompt: "What is the result of 3 * '2' in Python?",
    optionA: "6",
    optionB: "222",
    optionC: "Error",
    optionD: "32",
    answer: "B",
  },
  {
    prompt: "Which of the following is used to create a virtual environment?",
    optionA: "python -m venv env",
    optionB: "python create env",
    optionC: "pip virtualenv",
    optionD: "py new env",
    answer: "A",
  },
  {
    prompt: "Which operator is used for exponentiation?",
    optionA: "^",
    optionB: "**",
    optionC: "exp()",
    optionD: "//",
    answer: "B",
  },
  {
    prompt: "What is the output of: bool('')?",
    optionA: "True",
    optionB: "False",
    optionC: "None",
    optionD: "0",
    answer: "B",
  },
  {
    prompt: "Which method converts a string to lowercase?",
    optionA: "lower()",
    optionB: "down()",
    optionC: "small()",
    optionD: "reduce()",
    answer: "A",
  },
  {
    prompt: "What is the correct way to install a Python package?",
    optionA: "python install package",
    optionB: "pip install package",
    optionC: "py add package",
    optionD: "python -add package",
    answer: "B",
  },
];
